# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Waveform Playlist
email: naomiaro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Waveform Playlist: The multitrack javascript web audio editor and player.
baseurl: "/waveform-playlist" # the subpath of your site, e.g. /blog
url: "https://naomiaro.github.io" # the base hostname & protocol for your site
twitter_username: naomiaro
github_username: naomiaro

# Build settings
markdown: kramdown
collections:
  examples:
    output: true
    output_ext: html

